### ISSUE TITLE
Autocomplete doesn't work

### ISSUE THREAD

**Issue by mike-lev** [Hennamann/ExtendScript-for-Visual-Studio-Code#12]
I just installed the extension and noticed some strange behaviour.
If I open my existing script (.jsx) autocomplete works.
If I create a new .jsx file it doesn't.
What am I doing wrong?
Regards,
Michael

**Comment by Hennamann** [comment]
Late reply, but i will assume that this issue has been fixed in the latest release of the extension. 
If this is not the case please let me know so i can reopen the issue and investigate further.
