### ISSUE TITLE
Missing support for symbols

### ISSUE THREAD

**Issue by Harbs** [Hennamann/ExtendScript-for-Visual-Studio-Code#2]
The syntax highlighting seems to work correctly, but functions are not recognized as such.

"Go To Symbol in File" does not work for ExtendScript files.

Setting jsx files to Javascript without this extension enables symbols and works for the most part. The major exception is E4X.

FWIW, I've discovered that setting the type as ActionScript using the NextGenActionScript extension results in similar results to this.

If there's some way to enable symbols and keeping the syntax highlighting including E4X, that would make this extension really useful.

**Comment by Hennamann** [comment]
Hmmm, never tested symbols... I'll look at the source code for NextGenActionScript and see how they do it, if I have the time I'll get it added.

**Comment by Harbs** [comment]
To be clear, the symbols don't work in NextGenActionscript either.

The symbols **do** work if the language is plain _javascript_. I've never looked into VS Code languages, but if there's some way to make ExtendScript a version of Javascript with E4X as legal syntax, we should get the right results...

**Comment by Hennamann** [comment]
I see, if I'm lucky there's already an API in VSCode that I can use for this.

**Comment by Hennamann** [comment]
Yep, I'll have to make a custom DocumentSymbolProvider for extendscript files; the good news is I won't need to make too many changes from the default implementation to get something that works.

**Comment by Harbs** [comment]
Cool! Looking forward!

**Comment by svenax** [comment]
Any progress on this?

**Comment by ariestav** [comment]
@Hennamann Are there any updates to this? To get the symbols function to work, I'm setting .jsx files to "JavaScript" instead of "ExtendScript" but that causes issue with the editor because ExtendScript differs from JavaScript slightly.  This library does display all the ExtendScript correctly, but then the lack of symbol support does not make it usable.  Any idea when you might be able to fix it?  You mention last year that it wouldn't be terribly difficult.  If you point us in the right direction, we may be able to help implement.

Thanks!

**Comment by Hennamann** [comment]
Had to edit your comment to exclude the mention of Adobe projects that are currently under NDA.

I do hope to get back to work on this extension very soon and proper symbol support is at the top of my list. As mentioned all that is needed is to implement a custom DocumentSymbolProvider based on E4X. More information on that here: [https://code.visualstudio.com/api/references/vscode-api#DocumentSymbolProvider](https://code.visualstudio.com/api/references/vscode-api#DocumentSymbolProvider)

**Comment by ariestav** [comment]
Thanks for the edit, my oversight.  Thanks for the link.

**Comment by Hennamann** [comment]
Happy to report that this has now been fixed in the latest commit, a new version will be released shortly. e038fe89c57d5f8f366c3bbcd45354c12506d02d

Do note that the symbol support is based on es6/typescript so it may report weird symbols and errors in some places where es4 differs from es6.

**Comment by ariestav** [comment]
Amazing!  Thank you for your time and contributions to the community of devs — much appreciated.
