### ISSUE TITLE
Stopped working Win 11 VSC 1.62

### ISSUE THREAD

**Issue by schroef** [Hennamann/ExtendScript-for-Visual-Studio-Code#20]
Windows 11
VSC 1.62

Noticed it stopped working for me on Windows 11 using Visual Studio Code v1.62. I dont see any Syntax Highlight appear.
On OSX 10.11.6, i believe ive got older VSC, it still works

**Comment by kikili** [comment]
I have VSC 1.64.2 on Mac and it is not working as well

**Comment by Hennamann** [comment]
I don't have a windows 11 install available to test with right now but on vscode 1.66.2 the extension seems to work just fine with syntax highlighting...  Could you test in 1.66.2 and see if it's still an issue for you?

**Comment by Hennamann** [comment]
This is assumed to have been solved with the latest release of the extension. (1.3.0).
If this is not the case please comment so i can reopen the issue and investigate the issue further.

**Comment by schroef** [comment]
Sorry for the long wait. I was working at home with vsc again and noticed it again. Now update to 1.69.1 and dont see the syntax highlight? Should i get also descriptions of functions and variables as i hover over them?

Are there perhaps certain settings which i need to use?

I do get code hinting, thats from this extension right?
![vsc-extendscript syntax](https://user-images.githubusercontent.com/6923008/178749495-ea39ace0-9f9c-423a-9330-80f273cf7078.png)
