### ISSUE TITLE
Add document formatting + bugfix it

### ISSUE THREAD

**Issue by derrickb** [Hennamann/ExtendScript-for-Visual-Studio-Code#3]
When right-clicking in a jsx file, the useful "Format Document" feature is missing.

I believe it should be possible to instruct the extension to use the JavaScript formatter in the manifest but I haven't read too deeply into it.

For reference, this is what I'm referring to:
![image](https://user-images.githubusercontent.com/1793769/40726980-ccc9b95c-641e-11e8-9fa8-f00024968c00.png)

**Comment by Hennamann** [comment]
Interesting, i've never used the format document function personally, but i can look into getting it to work.

**Comment by derrickb** [comment]
Is there a way to configure the beautifier? It seems to be automatically converting my indentation from 2 spaces to 4.

**Comment by tonnyavery** [comment]
When trying to format the document I get
`Extension 'Prettier - Code Formatter' cannot format ...` error

**Comment by Hennamann** [comment]
Sorry about the late replies. I'll have to look into getting it configurable, shouldn't be too hard to do.

Not sure about that error, could you possibly send an example extendscript file to test?

**Comment by tonnyavery** [comment]
Well, it's basically any file for me, no matter what the content is
