### ISSUE TITLE
intellisense works?

### ISSUE THREAD

**Issue by rodrigotrovao** [Hennamann/ExtendScript-for-Visual-Studio-Code#4]
Im kinda new to all this.. git, visual code... does this shows intellisense for Extendscript?!

**Comment by Hennamann** [comment]
Hi sorry for getting back to you on this so late, the original version of this extension did not offer Intellisense, however the latest version (1.1.0) does offer Intellisense and other smart code features offered by Visual Studio Code.

**Comment by rodrigotrovao** [comment]
Oh thanks for answering! 👍
