### ISSUE TITLE
Breakpoints.

### ISSUE THREAD

**Issue by Andrei1911** [Hennamann/ExtendScript-for-Visual-Studio-Code#6]
I can't add breakpoints to my code. If i change the language to javascript, i can add them. Is this a problem on my side, or just general?

**Comment by timc3** [comment]
I get the same problem. Do you have the ExtendScript plugin installed?

**Comment by Hennamann** [comment]
This issue is only relevant if you have the official Adobe ExtendScript debugger extension installed. 

Not quite sure how to fix this, but i will look into it, and see what i can do.
