### ISSUE TITLE
Preprocessor directive errors

### ISSUE THREAD

**Issue by jimmyaffatigato** [Hennamann/ExtendScript-for-Visual-Studio-Code#7]
Attempting to use an #include statement in a script results in two errors.
Lines starting with # trigger error ts(1127) "Invalid character."
I'm also getting ts(1005) "';' Expected" because VSC thinks "include" is a variable name.

In ESTK, the syntax is as follows:
#include "somescript.jsx"

It's pretty low priority as it doesn't prevent the debugger from working correctly, but the red lines are distracting.

**Comment by Hennamann** [comment]
I'm aware of this, but the only way to fix this would be to create our own language server for extendscript, which I do not have the time nor capacity to do on my own. 
I do have a repository linked in the readme aiming to make a language server for extendscript but no progress has been made. But as you say it's far from a major bug.

**Comment by imsamuka** [comment]
An easy way to cover this is to use `//@include "script.jsx"` instead of `#include "script.jsx"`. As this is considered a comment, it solves both problems. This can be used for any Preprocessor directives.

**Comment by Hennamann** [comment]
I am closing this as i do not have the time nor capacity to create a language server for extendscript...
If one is made it will of course be integrated.
